config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products
  root "products#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :featured_image
    has_rich_text :description
    validates :name, presence: true
    validates :inventory_count, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  around_action :switch_locale

  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to @product
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.expect(product: [ :name, :description, :featured_image, :inventory_count ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Mystore" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if !user_signed_in? %>
  <p class="sign_in"><%= link_to "Login", new_user_session_path %></p>
  <% end %>
  <% if user_signed_in? %>
  <%= button_to "Đăng xuất", destroy_user_session_path, method: :delete %>
  <% end %>
  <%= link_to "Home", root_path %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</body>
</html>

app/views/products/_form.html.erb
<%= form_with model: product do |form| %>
    <div>
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    
    <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.rich_text_area :description %>
  </div>

  <div>
  <%= form.label :featured_image, style: "display: block" %>
  <%= form.file_field :featured_image, accept: "image/*" %>
</div>

<div>
    <%= form.label :inventory_count, style: "display: block" %>
    <%= form.number_field :inventory_count %>
  </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/products/edit.html.erb
<h1>Edit product</h1>

<%= render "form", product: @product %>
<%= link_to "Cancel", @product %>

app/views/products/index.html.erb
<h1><%= t ".title" %></h1>
    <% if user_signed_in? %>
        <%= link_to "New product", new_product_path %>
    <% end %>
    <div id="products">
        <% @products.each do |product| %>
            <div class="product-item">
                <%= link_to product.name, product %>
            </div>
        <% end %>
    </div>

app/views/products/new.html.erb
<h1>New product</h1>
<%= render "form", product: @product %>
<%= form_with model: @product do |form| %>
<%= link_to "Cancel", @product %>
<% end %>

app/views/products/show.html.erb
<div class="product-container">
        <h1><%= @product.name %></h1>
        <% if @product.featured_image.attached? %>
            <div class="product-image">
                <%= image_tag @product.featured_image %>
            </div>
        <% end %>
        <p class="product-description"><%= @product.description %></p>

        <div class="product-actions">
            <%= link_to "Back", products_path, class: "btn btn-back" %>
            <%= link_to "Edit", edit_product_path(@product), class: "btn btn-edit" %>
            <%= button_to "Delete", @product, method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "btn btn-delete" %>
        </div>
    </div>